version: 0.2

env:
  variables:
    VERSION_API: "v2"
    MY_AWS_REGION: "ap-southeast-1"
    MY_REPOSITORY_HOST: "627047936520.dkr.ecr.ap-southeast-1.amazonaws.com"
    MY_REPOSITORY_URI: "627047936520.dkr.ecr.ap-southeast-1.amazonaws.com/eks-demo"
    MY_DOCKERHUB_USERNAME: ""
    MY_DOCKERHUB_PASSWORD: ""

phases:
  pre_build:
    commands:
      - echo Pre_Build started on `date`
      - aws --version
      - aws ecr get-login-password --region $MY_AWS_REGION | docker login --username AWS --password-stdin $MY_REPOSITORY_HOST
      - COMMIT_SHORT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -b -8)
      - echo $(date +%Y%m%d) > /tmp/timestamp
      - DATETIME_CURRENT=$(echo $(cat /tmp/timestamp))
      - AUTHOR_EMAIL="$(git log -1 --pretty=%ae)"
      - VERSION_COMMIT=${VERSION_API}.${DATETIME_CURRENT}.${AUTHOR_EMAIL}.${COMMIT_SHORT_ID}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --platform=linux/amd64 -t $MY_REPOSITORY_URI:latest -f Dockerfile .
      - docker tag $MY_REPOSITORY_URI:latest $MY_REPOSITORY_URI:$VERSION_COMMIT
      - echo Writing image tag and set env variable file...
      - sed -i "s/IMAGE_TAG/$COMMIT_SHORT_ID/g" ./docker-compose.yml
      - cat docker-compose.yml

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $MY_REPOSITORY_URI:latest
      - docker push $MY_REPOSITORY_URI:$VERSION_COMMIT

artifacts:
  files:
    - "docker-compose.yml"
