version: 0.2

env:
  variables:
    MY_AWS_REGION: "ap-southeast-1"
    MY_REPOSITORY_HOST: "627047936520.dkr.ecr.ap-southeast-1.amazonaws.com"
    MY_REPOSITORY_URI: "627047936520.dkr.ecr.ap-southeast-1.amazonaws.com/eks-demo"
    MY_DOCKERHUB_USERNAME: ""
    MY_DOCKERHUB_PASSWORD: ""

phases:
  pre_build:
    commands:
      - echo Pre_Build started on `date`
      - aws --version
      - aws ecr get-login-password --region $MY_AWS_REGION | docker login --username AWS --password-stdin $MY_REPOSITORY_HOST
      - COMMIT_SHORT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -b -8)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $MY_REPOSITORY_URI:latest -f Dockerfile .
      - docker tag $MY_REPOSITORY_URI:latest $MY_REPOSITORY_URI:version-$COMMIT_SHORT_ID
      - echo Writing image tag and set env variable file...
      - cat docker-compose.yml

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $MY_REPOSITORY_URI:latest
      - docker push $MY_REPOSITORY_URI:version-$COMMIT_SHORT_ID

artifacts:
  files:
    - "docker-compose.yml"
